# Generated by Django 3.1 on 2021-02-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('className', models.CharField(blank=True, max_length=500, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('startTime', models.CharField(blank=True, max_length=20, null=True)),
                ('endTime', models.CharField(blank=True, max_length=20, null=True)),
                ('startRecur', models.DateTimeField(blank=True, null=True)),
                ('endRecur', models.DateTimeField(blank=True, null=True)),
                ('allDay', models.BooleanField(blank=True, null=True)),
                ('daysOfWeek', models.JSONField(default=list)),
                ('url', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
