# Generated by Django 3.1 on 2021-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sourcearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcearchive',
            name='status',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
